# Generated by Django 2.1.7 on 2019-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fendi', '0002_auto_20190317_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemshop',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
